### PR TITLE
backup: Also backup the crowbar database

### PR DESCRIPTION
**Pull request by vuntz**
This is important now that the proposals are saved there.

### CODE REVIEW

**Comment by bkutil** [comment]
+1

**Comment by aplanas** [comment]
Looks like that this is the missing piece for the backup / restore to work. Testing.

**Comment by dirkmueller** [comment]
+1

**Comment by vuntz** [comment]
Unfortunately, it's not enough because of https://github.com/SUSE-Cloud/cloud-tools/blob/master/backup/crowbar-backup#L302

I wonder if we can just remove the lines there; @aplanas could you test that?

**Comment by aplanas** [comment]
@vuntz Will test with this patch and lines 302-303 commented

**Comment by aplanas** [comment]
=== Successfully finished restore

Together with the removal of L302, L303:  +1

**Comment by nkrinner** [comment]
Works after removing the deletion of the sqlite production database. +1 assuming this gets added to the pr.

**Comment by vuntz** [comment]
@nkrinner See https://github.com/SUSE-Cloud/cloud-tools/pull/21 :-)

**Pull request merged**
